# Sample pre-commit configuration for PyDocGen Hook
repos:
-   repo: local
    hooks:
    -   id: pydocgen
        name: Generate docstrings for Python files
        entry: pydocgen
        language: python
        args: [--config=.pydocgen.yaml]  # Optional: specify docstring style
        # Additional arguments:
        # --style=google       # Google style docstrings
        # --include-private     # Include private methods
        # --config=.pydocgen.yaml  # Path to config file