# Sample pre-commit configuration for PyDocGen Hook
repos:
-   repo: https://github.com/gregahren/pydocgen
    rev: 0.1.0  # Use the latest version
    hooks:
    -   id: pydocgen
        args: [--style=google]  # Optional: specify docstring style, e.g., google, numpy, or rst
        # Additional arguments:
        # --include-private     # Include private methods
        # --config=.pydocgen.yaml  # Path to config file