# PyDocGen Hook Configuration

# Docstring style: google, numpy, or rst
style: google

# Verbosity level (1-3)
# 1: Basic docstrings with minimal information
# 2: Standard docstrings with detailed information
# 3: Comprehensive docstrings with extensive details
verbosity: 2

# Patterns to exclude from processing
exclude:
  - tests/*
  - setup.py
  - __init__.py
  - conftest.py

# Whether to include private methods (prefixed with _)
include_private: false